### ISSUE TITLE
Where to import sha3 from?

### ISSUE THREAD

**Issue by ldo** [bramcohen/DissidentX#5]
The first few lines of DissidentXEncoding.py currently look like this:

```
import hashlib
import sha3

...

def h(message):
    return hashlib.sha3_256(message).digest()
```

On my Debian Unstable installation, hashlib does not have a member named sha3_256. But the sha3 import is unused; should the call to hashlab.sha3_256 actually be a call to something in module sha3?

**Comment by bramcohen** [comment]
From the first two lines of DissidentXEncoding - 

# http://pypi.python.org/pypi/pycrypto

# http://pypi.python.org/pypi/pysha3/

You have to install both of those to get all of the dependencies.
